import { JourneyStep } from '@/components/LuxuryJourneyMap'

export interface ProductJourney {
  productId: string
  productName: string
  description: string
  steps: JourneyStep[]
}

// Generic journey steps that can be customized per product
export const JOURNEY_STEPS: Record<string, JourneyStep> = {
  // AI Voice Clone Journey
  'voice-step-1': {
    id: 1,
    title: 'Describe Your Story',
    description: 'Tell us about your voice, your style, and what you want to create. Our AI learns your unique vocal characteristics.',
    icon: '🎤',
    details: [
      'Record a 30-second voice sample',
      'Describe your vocal style and characteristics',
      'Choose your preferred accent and tone',
      'Set emotional parameters (happy, serious, energetic, etc.)',
    ],
    duration: '5-10 minutes',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },
  'voice-step-2': {
    id: 2,
    title: 'AI Emotional Analysis',
    description: 'Our advanced AI analyzes your voice patterns, emotional nuances, and speaking characteristics to create a perfect digital clone.',
    icon: '🧠',
    details: [
      'Analyze vocal patterns and frequencies',
      'Map emotional expressions and intonations',
      'Learn pronunciation preferences',
      'Calibrate voice quality and naturalness',
    ],
    duration: '2-3 minutes',
    color: 'rgba(147, 112, 219, 1)',
    glowColor: 'rgba(147, 112, 219, 0.3)',
  },
  'voice-step-3': {
    id: 3,
    title: 'Creative Generation',
    description: 'Generate unlimited voiceovers, narrations, and audio content in your voice. Create, edit, and perfect your content instantly.',
    icon: '🎨',
    details: [
      'Generate voiceovers from text',
      'Create multiple takes and variations',
      'Adjust pace, emotion, and emphasis',
      'Add sound effects and background music',
    ],
    duration: '1-2 minutes per generation',
    color: 'rgba(255, 107, 107, 1)',
    glowColor: 'rgba(255, 107, 107, 0.3)',
  },
  'voice-step-4': {
    id: 4,
    title: 'Quality Review',
    description: 'Review, refine, and perfect your generated content. Compare multiple versions and make final adjustments.',
    icon: '✨',
    details: [
      'Listen to generated audio',
      'Compare different variations',
      'Fine-tune pronunciation and emotion',
      'Add final polish and effects',
    ],
    duration: '3-5 minutes',
    color: 'rgba(76, 175, 80, 1)',
    glowColor: 'rgba(76, 175, 80, 0.3)',
  },
  'voice-step-5': {
    id: 5,
    title: 'Delivery & Distribution',
    description: 'Download your content in multiple formats and distribute across all platforms. Your voice is ready for the world.',
    icon: '🎁',
    details: [
      'Download in MP3, WAV, or other formats',
      'Export with metadata and timestamps',
      'Auto-upload to YouTube, Spotify, etc.',
      'Track analytics and engagement',
    ],
    duration: '1 minute',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },

  // AI Music Producer Journey
  'music-step-1': {
    id: 1,
    title: 'Describe Your Sound',
    description: 'Tell us what kind of music you want to create. Choose genre, mood, instruments, and style preferences.',
    icon: '🎵',
    details: [
      'Select music genre (pop, hip-hop, electronic, etc.)',
      'Choose mood and energy level',
      'Pick preferred instruments and sounds',
      'Set tempo and key preferences',
    ],
    duration: '3-5 minutes',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },
  'music-step-2': {
    id: 2,
    title: 'AI Emotional Analysis',
    description: 'Our AI analyzes your preferences and creates a personalized music generation model that matches your creative vision.',
    icon: '🧠',
    details: [
      'Analyze your music preferences',
      'Learn your creative style',
      'Map emotional and dynamic preferences',
      'Create personalized generation model',
    ],
    duration: '2-3 minutes',
    color: 'rgba(147, 112, 219, 1)',
    glowColor: 'rgba(147, 112, 219, 0.3)',
  },
  'music-step-3': {
    id: 3,
    title: 'Creative Generation',
    description: 'Generate unlimited original music tracks. Create variations, remixes, and new compositions instantly.',
    icon: '🎨',
    details: [
      'Generate original music tracks',
      'Create multiple variations',
      'Adjust structure and arrangement',
      'Mix and layer different elements',
    ],
    duration: '1-2 minutes per track',
    color: 'rgba(255, 107, 107, 1)',
    glowColor: 'rgba(255, 107, 107, 0.3)',
  },
  'music-step-4': {
    id: 4,
    title: 'Quality Review',
    description: 'Review, refine, and perfect your music. Compare versions, adjust mixing, and add final touches.',
    icon: '✨',
    details: [
      'Listen to generated tracks',
      'Compare different versions',
      'Adjust mixing and mastering',
      'Add final production touches',
    ],
    duration: '3-5 minutes',
    color: 'rgba(76, 175, 80, 1)',
    glowColor: 'rgba(76, 175, 80, 0.3)',
  },
  'music-step-5': {
    id: 5,
    title: 'Delivery & Distribution',
    description: 'Download your music and distribute to all major streaming platforms. Start earning royalties immediately.',
    icon: '🎁',
    details: [
      'Download in WAV, MP3, or FLAC',
      'Export with metadata and tags',
      'Auto-upload to Spotify, Apple Music, etc.',
      'Track streams and earnings',
    ],
    duration: '1 minute',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },

  // AI Music Video Journey
  'video-step-1': {
    id: 1,
    title: 'Describe Your Vision',
    description: 'Tell us about your music video concept. Choose style, aesthetic, and visual themes.',
    icon: '🎬',
    details: [
      'Describe your video concept',
      'Choose visual style and aesthetic',
      'Select color palette and mood',
      'Pick camera movements and effects',
    ],
    duration: '5-10 minutes',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },
  'video-step-2': {
    id: 2,
    title: 'AI Emotional Analysis',
    description: 'Our AI analyzes your music and creates a visual narrative that perfectly matches your song\'s emotion and energy.',
    icon: '🧠',
    details: [
      'Analyze music structure and emotion',
      'Map visual narrative to song beats',
      'Create emotional visual journey',
      'Generate scene descriptions',
    ],
    duration: '2-3 minutes',
    color: 'rgba(147, 112, 219, 1)',
    glowColor: 'rgba(147, 112, 219, 0.3)',
  },
  'video-step-3': {
    id: 3,
    title: 'Creative Generation',
    description: 'Generate stunning 4K music video with cinematic visuals, effects, and transitions that match your music perfectly.',
    icon: '🎨',
    details: [
      'Generate video scenes and sequences',
      'Create smooth transitions',
      'Add visual effects and overlays',
      'Sync visuals to music beats',
    ],
    duration: '5-10 minutes',
    color: 'rgba(255, 107, 107, 1)',
    glowColor: 'rgba(255, 107, 107, 0.3)',
  },
  'video-step-4': {
    id: 4,
    title: 'Quality Review',
    description: 'Review your video, make adjustments, and perfect every frame. Compare versions and finalize your masterpiece.',
    icon: '✨',
    details: [
      'Watch full video preview',
      'Compare different style options',
      'Adjust effects and transitions',
      'Fine-tune color and lighting',
    ],
    duration: '5-10 minutes',
    color: 'rgba(76, 175, 80, 1)',
    glowColor: 'rgba(76, 175, 80, 0.3)',
  },
  'video-step-5': {
    id: 5,
    title: 'Delivery & Distribution',
    description: 'Download your 4K music video and share it everywhere. Watch it go viral on YouTube, TikTok, and Instagram.',
    icon: '🎁',
    details: [
      'Download in 4K, 1080p, or 720p',
      'Export with subtitles and metadata',
      'Auto-upload to YouTube, TikTok, etc.',
      'Track views and engagement',
    ],
    duration: '1 minute',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },

  // AI Podcast Producer Journey
  'podcast-step-1': {
    id: 1,
    title: 'Describe Your Podcast',
    description: 'Tell us about your podcast concept, topics, and style. Set up your podcast format and preferences.',
    icon: '🎙️',
    details: [
      'Choose podcast topic and niche',
      'Describe your hosting style',
      'Set episode format and length',
      'Choose intro/outro music style',
    ],
    duration: '5-10 minutes',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },
  'podcast-step-2': {
    id: 2,
    title: 'AI Emotional Analysis',
    description: 'Our AI learns your podcast style and creates a personalized production model that matches your voice and tone.',
    icon: '🧠',
    details: [
      'Analyze your speaking style',
      'Learn your podcast format',
      'Map episode structure and pacing',
      'Create production templates',
    ],
    duration: '2-3 minutes',
    color: 'rgba(147, 112, 219, 1)',
    glowColor: 'rgba(147, 112, 219, 0.3)',
  },
  'podcast-step-3': {
    id: 3,
    title: 'Creative Generation',
    description: 'Generate complete podcast episodes with narration, music, sound effects, and professional editing.',
    icon: '🎨',
    details: [
      'Generate episode narration',
      'Add background music and effects',
      'Create smooth transitions',
      'Auto-edit and master audio',
    ],
    duration: '3-5 minutes per episode',
    color: 'rgba(255, 107, 107, 1)',
    glowColor: 'rgba(255, 107, 107, 0.3)',
  },
  'podcast-step-4': {
    id: 4,
    title: 'Quality Review',
    description: 'Review your episode, make adjustments, and ensure professional quality before publishing.',
    icon: '✨',
    details: [
      'Listen to full episode',
      'Adjust pacing and emphasis',
      'Fine-tune audio levels',
      'Add final polish',
    ],
    duration: '3-5 minutes',
    color: 'rgba(76, 175, 80, 1)',
    glowColor: 'rgba(76, 175, 80, 0.3)',
  },
  'podcast-step-5': {
    id: 5,
    title: 'Delivery & Distribution',
    description: 'Publish your episode to all major podcast platforms. Reach millions of listeners automatically.',
    icon: '🎁',
    details: [
      'Download in MP3 or WAV',
      'Auto-upload to Spotify, Apple Podcasts',
      'Generate show notes and transcripts',
      'Track downloads and listeners',
    ],
    duration: '1 minute',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },

  // AI Artist Label Journey
  'label-step-1': {
    id: 1,
    title: 'Describe Your Label',
    description: 'Tell us about your music label, artists, and catalog. Set up your label profile and preferences.',
    icon: '🏷️',
    details: [
      'Name your music label',
      'Describe your label\'s style',
      'Add artists to your label',
      'Set catalog and distribution preferences',
    ],
    duration: '5-10 minutes',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },
  'label-step-2': {
    id: 2,
    title: 'AI Emotional Analysis',
    description: 'Our AI analyzes your label\'s brand and creates a personalized distribution and marketing strategy.',
    icon: '🧠',
    details: [
      'Analyze your label\'s brand identity',
      'Learn your target audience',
      'Map marketing and distribution strategy',
      'Create growth projections',
    ],
    duration: '2-3 minutes',
    color: 'rgba(147, 112, 219, 1)',
    glowColor: 'rgba(147, 112, 219, 0.3)',
  },
  'label-step-3': {
    id: 3,
    title: 'Creative Generation',
    description: 'Generate marketing materials, artwork, and promotional content for your releases.',
    icon: '🎨',
    details: [
      'Generate album artwork and covers',
      'Create promotional graphics',
      'Generate marketing copy',
      'Create social media content',
    ],
    duration: '2-3 minutes per release',
    color: 'rgba(255, 107, 107, 1)',
    glowColor: 'rgba(255, 107, 107, 0.3)',
  },
  'label-step-4': {
    id: 4,
    title: 'Quality Review',
    description: 'Review all marketing materials and release information before publishing to streaming platforms.',
    icon: '✨',
    details: [
      'Review artwork and metadata',
      'Check promotional materials',
      'Verify artist information',
      'Confirm distribution settings',
    ],
    duration: '3-5 minutes',
    color: 'rgba(76, 175, 80, 1)',
    glowColor: 'rgba(76, 175, 80, 0.3)',
  },
  'label-step-5': {
    id: 5,
    title: 'Delivery & Distribution',
    description: 'Distribute your releases to all major streaming platforms and start earning royalties.',
    icon: '🎁',
    details: [
      'Distribute to Spotify, Apple Music, etc.',
      'Track streams and earnings',
      'Generate royalty reports',
      'Manage artist payments',
    ],
    duration: '1 minute',
    color: 'rgba(212, 175, 55, 1)',
    glowColor: 'rgba(212, 175, 55, 0.3)',
  },
}

// Product-specific journeys
export const PRODUCT_JOURNEYS: Record<string, ProductJourney> = {
  'ai-voice-clone': {
    productId: 'ai-voice-clone',
    productName: 'AI Voice Clone',
    description: 'Your voice, immortalized. Create unlimited voiceovers in your voice.',
    steps: [
      JOURNEY_STEPS['voice-step-1'],
      JOURNEY_STEPS['voice-step-2'],
      JOURNEY_STEPS['voice-step-3'],
      JOURNEY_STEPS['voice-step-4'],
      JOURNEY_STEPS['voice-step-5'],
    ],
  },
  'ai-music-producer': {
    productId: 'ai-music-producer',
    productName: 'AI Music Producer',
    description: 'Generate unlimited original music in any genre, style, or mood.',
    steps: [
      JOURNEY_STEPS['music-step-1'],
      JOURNEY_STEPS['music-step-2'],
      JOURNEY_STEPS['music-step-3'],
      JOURNEY_STEPS['music-step-4'],
      JOURNEY_STEPS['music-step-5'],
    ],
  },
  'ai-music-video': {
    productId: 'ai-music-video',
    productName: 'AI Music Video',
    description: 'Create stunning 4K music videos with cinematic visuals.',
    steps: [
      JOURNEY_STEPS['video-step-1'],
      JOURNEY_STEPS['video-step-2'],
      JOURNEY_STEPS['video-step-3'],
      JOURNEY_STEPS['video-step-4'],
      JOURNEY_STEPS['video-step-5'],
    ],
  },
  'ai-podcast-producer': {
    productId: 'ai-podcast-producer',
    productName: 'AI Podcast Producer',
    description: 'Generate, edit, and distribute podcast episodes automatically.',
    steps: [
      JOURNEY_STEPS['podcast-step-1'],
      JOURNEY_STEPS['podcast-step-2'],
      JOURNEY_STEPS['podcast-step-3'],
      JOURNEY_STEPS['podcast-step-4'],
      JOURNEY_STEPS['podcast-step-5'],
    ],
  },
  'ai-artist-label': {
    productId: 'ai-artist-label',
    productName: 'AI Artist Label',
    description: 'Your independent music label. Distribute, monetize, and grow your catalog.',
    steps: [
      JOURNEY_STEPS['label-step-1'],
      JOURNEY_STEPS['label-step-2'],
      JOURNEY_STEPS['label-step-3'],
      JOURNEY_STEPS['label-step-4'],
      JOURNEY_STEPS['label-step-5'],
    ],
  },
}
